name: Integration

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm i
        run: npm i
      - name: npm run build
        run: npm run build
