name: Production

on:
  push:
    branches:
      - 'master'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: bahmutov/npm-install@master
      - run: npm run build
      - uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting,firestore:rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - uses: 8398a7/action-slack@master
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
