name: Production

on:
  push:
    branches:
      - 'master'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Cache modules
        id: node_modules_cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            **/node_modules
          key: node-${{ hashFiles('**/package-lock.json') }}
      - name: Install modules
        if: steps.node_modules_cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build
        run: npm run build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting,firestore:rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          fields: repo,author,message,workflow,took
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
